name = "hankg-hyde-hyde"
license = "MIT"
licenselink = "https://github.com/hankg/hyde-hyde/blob/master/LICENSE.md"
description = "A simply cool Hyde inspired theme"
tags = ["blog", "theme", "hyde", "highlight.js", "font-awesome", "google analytics", "disqus", "personal", "syntax highlighting", "responsive", "graphcomment"]
features = ["blog", "theme", "highlight.js", "font-awesome", "responsive", "disqus", "graphcomment", "portfolio"]
homepage = "https://github.com/hankg/hyde-hyde"
min_version = "0.43"

[author]
    name = "hankg"
    homepage = "https://nequalsonelifestyle.com"

# If Porting existing theme
[original]
    author =  "htr3n"
    homepage = "https://htr3n.github.io"
    repo = "https://github.com/htr3n/hyde-hyde"
