## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"

title = "Title"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
### Main Parameters
[params]
    author = "Author"
    title = "Title"
    # description = "..."
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    # themeColor = "theme-base-08"

    # sidebar, copyright & license
    #logoimage = "/img/hugo.png"
    copyright = "htr3n"
    since = 2019
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true
    # includeFontAwesome = true

    # Go to HighlightJS site for styles and language options: https://highlightjs.org
    # highlightjs = true
    # highlightjsstyle = "base16/zenburn"
    # highlightjslanguages = ["bash", "java"]
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"


### Markup
#### Chroma Style options gallery: https://xyproto.github.io/splash/docs/
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'tango'
    tabWidth = 4


## Social Accounts
[params.social]
    # aboutme = "<username>"
    # bitbucket = "<username>"
    # email = "your-email@example.com"
    # facebook = "<username>"
    github = "<username>"
    gitlab = "<username>"
    # custom_gitlab_domain = "gitlab.example.com"
    # googlescholar = "<user_id_code>"
    instagram = "<username>"
    # keybase = "<username>"
    # linkedin = "<username>"
    # medium = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    # pgpkey = "<path-to-your-key-in-/static>"
    # reddit = "<username>"
    rss = "<url>"
    # telegram = "<username>"
    twitter = "<username>"
    # microblog = "<username>"
    # stackoverflow = "<username>"
    # xing = "<username>"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
