## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"

title = "Title"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
### Main Parameters
[params]
    author = "Author"
    title = "Title"
    # description = "..."
    authorimage = "/img/hugo.png"
    
    # Uncomment for default OpenGraph images
    # Add similar field to post to override w/ post specific ones
    # images = ["/img/hugo.png"]
    dateformat = "Jan 2, 2006"
    # themeColor = "theme-base-08"

    # sidebar, copyright & license
    #logoimage = "/img/hugo.png"
    copyright = "htr3n"
    since = 2019
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true
    # includeFontAwesome = true

    # Go to HighlightJS site for styles and language options: https://highlightjs.org
    # highlightjs = true
    # highlightjsstyle = "base16/zenburn"
    # highlightjslanguages = ["bash", "java"]
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    # aboutme = "<about.me_username>"
    # bandcamp = "<bandcamp_url>"
    # behance = "<behance_username>"
    # bitbucket = "<bitbucket_username>"
    # blogspot = "<blogspot_site_name>"
    # dailymotion = "<dailymotion_username>"
    # devto = "<devto_username>"
    # deviantart = "<deviantart_username>"
    # diaspora = "<diaspora_url>"
    email = "your-email@example.com"
    # etsy = "<shop_name>"
    # facebook = "<facebook_username>"
    # flickr = "<flickr_url>"
    # funkwhale = "<funkwhale.url>"
    # friendica = "<friendica.url>"
    github = "<github_username>"
    gitlab = "<gitlab_username>"
    # custom_gitlab_domain = "gitlab.example.com"
    # gnusocial = "<gnusocial_url>"
    # goodreads = "<goodreads_url>"
    # googlescholar = "<google_scholar_user_id_code>"
    # hubzilla = "<hubzilla_url>"
    # instagram = "<instagram_username>"
    # kaggle = "<kaggle_username>"
    # keybase = "<keybase_username>"
    # kickstarter = "<kickstarter_url>"
    linkedin = "<linkedin_username>"
    # mastodon = "<mastodon_url>"
    # medium = "<medium_username>"
    # microblog = "<microblog_username>"
    # misskey = "<misskey_url>"
    # odnoklassniki = "<odnoklassniki_url>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    # patreon = "<patreon_url>"
    # peertube = "<peertube_url>"
    # pixelfed = "<pixelfed_url>"
    # pleroma = "<pleroma_url>"
    # pgpkey = "<path-to-your-key-in-/static>"
    # pinterest = "<pinterest_url>"
    # reddit = "<reddit_username>"
    # researchgate = "<researchgate_username>"
    # socialhome = "<socialhome_url>"
    # telegram = "<utelegram_sername>"
    # tiktok = "<tiktok_username>"
    # tumblr = "<tumblr_url>"
    twitch = "<twitch_url>"
    twitter = "<twitter_username>"
    # stackoverflow = "<stackoverflow_username>"
    # xing = "<xing_username>"
    # youtube = "<youtube_url>"
    
    rss = "index.xml" # Default for the siteChange if want to point to another RSS location
    gravatar = "your-email@example.com"

### Markup
#### Chroma Style options gallery: https://xyproto.github.io/splash/docs/
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'tango'
    tabWidth = 4


## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
